package com.istratenkov.energyregistration.repository;

import com.istratenkov.energyregistration.model.entity.Fraction;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Spring data repository for given entity Fraction.
 * All crud methods and others is generated by spring data.
 */
@Repository
public interface FractionRepository extends CrudRepository<Fraction, Long> {
    /**
     * Finds all fractions for given profile and specific year.
     * @param profileId profileId stored in database.
     * @param year year for fraction search in database.
     * @return all fractions that matched from db or empty collection.
     */
    List<Fraction> findAllByProfileIdAndYear(Long profileId, Integer year);
}
