package com.istratenkov.energyregistration.repository;

import com.istratenkov.energyregistration.model.entity.MeterMeasurement;
import com.istratenkov.energyregistration.model.entity.enumeration.Month;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Spring data repository for given entity MeterMeasurement.
 * All crud methods and others is generated by spring data.
 */
@Repository
public interface MeterMeasurementRepository extends CrudRepository<MeterMeasurement, Long> {

    /**
     * Finds all measurements for given profile and specific year, in given months.
     *
     * @param profileId profileId stored in database.
     * @param year      year for measurement search in database.
     * @param months    list of month that needed the information.
     * @return all measurements from db that matched or empty collection.
     */
    List<MeterMeasurement> findAllByProfileIdAndYearAndMonthIn(Long profileId, Integer year, List<Month> months);

    /**
     * Finds all measurements for given profile and specific year.
     *
     * @param profileId profileId stored in database.
     * @param year      year for measurement search in database.
     * @return all measurements from db that matched or empty collection.
     */
    List<MeterMeasurement> findAllByProfileIdAndYear(Long profileId, Integer year);
}
